version: '3'
name: canvas-manager
services:
  fastapi:
    build: backend/
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
