apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: money-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: alphashow/money-manager-fastapi:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: money-manager-config
