apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: money-manager
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres