apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: money-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.1-alpine3.18
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: money-manager-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc